version: 1.2
workflows:
- name: ONT_DemuxAndQC
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_DemuxAndQC.wdl
- name: ONT_ReadPrepAndQC
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_ReadPrepAndQC.wdl
- name: ONT_AssembleCanu
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_AssembleCanu.wdl