version: 1.2
workflows:
  - name: ONT_PreprocessingAndRunQC
    subclass: wdl
    primaryDescriptorPath: /wdls/pipelines/ONT_PreprocessingAndRunQC.wdl
  - name: ONT_ReadPrepAndQC
<<<<<<< HEAD
    subclass: WDL
    primaryDescriptorPath: wdls/pipelines/ONT_ReadPrepAndQC.wdl
=======
    subclass: wdl
    primaryDescriptorPath: /wdls/pipelines/ONT_ReadPrepAndQC.wdl
>>>>>>> 02ef3d88aaaedc4bf22111c182c5e905d986effa
