version: 1.2
workflows:
  - name: ONT_PreprocessingAndRunQC
    subclass: wdl
    primaryDescriptorPath: /wdls/pipelines/ONT_PreprocessingAndRunQC.wdl
  - name: ONT_ReadPrepAndQC
    subclass: wdl
    primaryDescriptorPath: /wdls/pipelines/ONT_ReadPrepAndQC.wdl
