version: 1.2
workflows:
- name: ONT_DemuxAndQC__deprecated
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_DemuxAndQC__deprecated.wdl
- name: ONT_ReadPrepAndQC
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_ReadPrepAndQC.wdl
- name: ONT_AssembleCanu
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_AssembleCanu.wdl
- name: ONT_BAMtoFastq
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/ONT_BAMtoFastq.wdl

