version: 1.2
workflows:
  - name: ONT_AssembleCanu
    subclass: wdl
    primaryDescriptorPath: /wdls/pipelines/ONT_AssembleCanu.wdl
    latestTagAsDefault: 'true'
  - name: ONT_BAMtoFastq
    subclass: wdl
    primaryDescriptorPath: /wdls/pipelines/ONT_BAMtoFastq.wdl

    latestTagAsDefault: 'true'
